//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.06 at 08:04:05 PM GMT+04:00 
//


package Schemas;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EntityTypes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EntityTypes">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ElderGuardian"/>
 *     &lt;enumeration value="WitherSkeleton"/>
 *     &lt;enumeration value="Stray"/>
 *     &lt;enumeration value="Husk"/>
 *     &lt;enumeration value="ZombieVillager"/>
 *     &lt;enumeration value="SkeletonHorse"/>
 *     &lt;enumeration value="ZombieHorse"/>
 *     &lt;enumeration value="EvocationIllager"/>
 *     &lt;enumeration value="VindicationIllager"/>
 *     &lt;enumeration value="Vex"/>
 *     &lt;enumeration value="Creeper"/>
 *     &lt;enumeration value="Skeleton"/>
 *     &lt;enumeration value="Spider"/>
 *     &lt;enumeration value="Giant"/>
 *     &lt;enumeration value="Zombie"/>
 *     &lt;enumeration value="Slime"/>
 *     &lt;enumeration value="Ghast"/>
 *     &lt;enumeration value="PigZombie"/>
 *     &lt;enumeration value="Enderman"/>
 *     &lt;enumeration value="CaveSpider"/>
 *     &lt;enumeration value="Silverfish"/>
 *     &lt;enumeration value="Blaze"/>
 *     &lt;enumeration value="LavaSlime"/>
 *     &lt;enumeration value="EnderDragon"/>
 *     &lt;enumeration value="WitherBoss"/>
 *     &lt;enumeration value="Bat"/>
 *     &lt;enumeration value="Witch"/>
 *     &lt;enumeration value="Endermite"/>
 *     &lt;enumeration value="Guardian"/>
 *     &lt;enumeration value="Shulker"/>
 *     &lt;enumeration value="Donkey"/>
 *     &lt;enumeration value="Mule"/>
 *     &lt;enumeration value="Pig"/>
 *     &lt;enumeration value="Sheep"/>
 *     &lt;enumeration value="Cow"/>
 *     &lt;enumeration value="Chicken"/>
 *     &lt;enumeration value="Squid"/>
 *     &lt;enumeration value="Wolf"/>
 *     &lt;enumeration value="MushroomCow"/>
 *     &lt;enumeration value="SnowMan"/>
 *     &lt;enumeration value="Ozelot"/>
 *     &lt;enumeration value="VillagerGolem"/>
 *     &lt;enumeration value="Horse"/>
 *     &lt;enumeration value="Rabbit"/>
 *     &lt;enumeration value="PolarBear"/>
 *     &lt;enumeration value="Llama"/>
 *     &lt;enumeration value="Villager"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EntityTypes")
@XmlEnum
public enum EntityTypes {

    @XmlEnumValue("ElderGuardian")
    ELDER_GUARDIAN("ElderGuardian"),
    @XmlEnumValue("WitherSkeleton")
    WITHER_SKELETON("WitherSkeleton"),
    @XmlEnumValue("Stray")
    STRAY("Stray"),
    @XmlEnumValue("Husk")
    HUSK("Husk"),
    @XmlEnumValue("ZombieVillager")
    ZOMBIE_VILLAGER("ZombieVillager"),
    @XmlEnumValue("SkeletonHorse")
    SKELETON_HORSE("SkeletonHorse"),
    @XmlEnumValue("ZombieHorse")
    ZOMBIE_HORSE("ZombieHorse"),
    @XmlEnumValue("EvocationIllager")
    EVOCATION_ILLAGER("EvocationIllager"),
    @XmlEnumValue("VindicationIllager")
    VINDICATION_ILLAGER("VindicationIllager"),
    @XmlEnumValue("Vex")
    VEX("Vex"),
    @XmlEnumValue("Creeper")
    CREEPER("Creeper"),
    @XmlEnumValue("Skeleton")
    SKELETON("Skeleton"),
    @XmlEnumValue("Spider")
    SPIDER("Spider"),
    @XmlEnumValue("Giant")
    GIANT("Giant"),
    @XmlEnumValue("Zombie")
    ZOMBIE("Zombie"),
    @XmlEnumValue("Slime")
    SLIME("Slime"),
    @XmlEnumValue("Ghast")
    GHAST("Ghast"),
    @XmlEnumValue("PigZombie")
    PIG_ZOMBIE("PigZombie"),
    @XmlEnumValue("Enderman")
    ENDERMAN("Enderman"),
    @XmlEnumValue("CaveSpider")
    CAVE_SPIDER("CaveSpider"),
    @XmlEnumValue("Silverfish")
    SILVERFISH("Silverfish"),
    @XmlEnumValue("Blaze")
    BLAZE("Blaze"),
    @XmlEnumValue("LavaSlime")
    LAVA_SLIME("LavaSlime"),
    @XmlEnumValue("EnderDragon")
    ENDER_DRAGON("EnderDragon"),
    @XmlEnumValue("WitherBoss")
    WITHER_BOSS("WitherBoss"),
    @XmlEnumValue("Bat")
    BAT("Bat"),
    @XmlEnumValue("Witch")
    WITCH("Witch"),
    @XmlEnumValue("Endermite")
    ENDERMITE("Endermite"),
    @XmlEnumValue("Guardian")
    GUARDIAN("Guardian"),
    @XmlEnumValue("Shulker")
    SHULKER("Shulker"),
    @XmlEnumValue("Donkey")
    DONKEY("Donkey"),
    @XmlEnumValue("Mule")
    MULE("Mule"),
    @XmlEnumValue("Pig")
    PIG("Pig"),
    @XmlEnumValue("Sheep")
    SHEEP("Sheep"),
    @XmlEnumValue("Cow")
    COW("Cow"),
    @XmlEnumValue("Chicken")
    CHICKEN("Chicken"),
    @XmlEnumValue("Squid")
    SQUID("Squid"),
    @XmlEnumValue("Wolf")
    WOLF("Wolf"),
    @XmlEnumValue("MushroomCow")
    MUSHROOM_COW("MushroomCow"),
    @XmlEnumValue("SnowMan")
    SNOW_MAN("SnowMan"),
    @XmlEnumValue("Ozelot")
    OZELOT("Ozelot"),
    @XmlEnumValue("VillagerGolem")
    VILLAGER_GOLEM("VillagerGolem"),
    @XmlEnumValue("Horse")
    HORSE("Horse"),
    @XmlEnumValue("Rabbit")
    RABBIT("Rabbit"),
    @XmlEnumValue("PolarBear")
    POLAR_BEAR("PolarBear"),
    @XmlEnumValue("Llama")
    LLAMA("Llama"),
    @XmlEnumValue("Villager")
    VILLAGER("Villager");
    private final String value;

    EntityTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EntityTypes fromValue(String v) {
        for (EntityTypes c: EntityTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
