//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.06 at 08:04:05 PM GMT+04:00 
//


package Schemas;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Facing.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Facing">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="DOWN"/>
 *     &lt;enumeration value="UP"/>
 *     &lt;enumeration value="NORTH"/>
 *     &lt;enumeration value="SOUTH"/>
 *     &lt;enumeration value="WEST"/>
 *     &lt;enumeration value="EAST"/>
 *     &lt;enumeration value="UP_X"/>
 *     &lt;enumeration value="DOWN_X"/>
 *     &lt;enumeration value="UP_Z"/>
 *     &lt;enumeration value="DOWN_Z"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Facing")
@XmlEnum
public enum Facing {

    DOWN,
    UP,
    NORTH,
    SOUTH,
    WEST,
    EAST,
    UP_X,
    DOWN_X,
    UP_Z,
    DOWN_Z;

    public String value() {
        return name();
    }

    public static Facing fromValue(String v) {
        return valueOf(v);
    }

}
