//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.06 at 08:04:05 PM GMT+04:00 
//


package Schemas;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GameMode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="GameMode">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Survival"/>
 *     &lt;enumeration value="Creative"/>
 *     &lt;enumeration value="Adventure"/>
 *     &lt;enumeration value="Spectator"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "GameMode")
@XmlEnum
public enum GameMode {

    @XmlEnumValue("Survival")
    SURVIVAL("Survival"),
    @XmlEnumValue("Creative")
    CREATIVE("Creative"),
    @XmlEnumValue("Adventure")
    ADVENTURE("Adventure"),
    @XmlEnumValue("Spectator")
    SPECTATOR("Spectator");
    private final String value;

    GameMode(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GameMode fromValue(String v) {
        for (GameMode c: GameMode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
