//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.06 at 08:04:05 PM GMT+04:00 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://ProjectMalmo.microsoft.com", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package Schemas;
