//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.06 at 08:04:05 PM GMT+04:00 
//


package Schemas;

import java.math.BigDecimal;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RandomPlacement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RandomPlacement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="origin" type="{http://ProjectMalmo.microsoft.com}Pos" minOccurs="0"/>
 *         &lt;element name="minRadius" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="maxRadius" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="block" type="{http://ProjectMalmo.microsoft.com}BlockType"/>
 *         &lt;element name="placement" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="sphere"/>
 *               &lt;enumeration value="circle"/>
 *               &lt;enumeration value="surface"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="randomizedRadius" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="minRandomizedRadius" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="maxRandomizedRadius" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RandomPlacement", propOrder = {

})
public class RandomPlacement {

    protected Pos origin;
    @XmlElement(required = true)
    protected BigDecimal minRadius;
    @XmlElement(required = true)
    protected BigDecimal maxRadius;
    @XmlElement(required = true)
    protected BlockType block;
    protected String placement;
    @XmlElement(defaultValue = "false")
    protected Boolean randomizedRadius;
    @XmlElement(defaultValue = "10")
    protected BigDecimal minRandomizedRadius;
    @XmlElement(defaultValue = "64")
    protected BigDecimal maxRandomizedRadius;

    /**
     * Gets the value of the origin property.
     * 
     * @return
     *     possible object is
     *     {@link Pos }
     *     
     */
    public Pos getOrigin() {
        return origin;
    }

    /**
     * Sets the value of the origin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pos }
     *     
     */
    public void setOrigin(Pos value) {
        this.origin = value;
    }

    /**
     * Gets the value of the minRadius property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMinRadius() {
        return minRadius;
    }

    /**
     * Sets the value of the minRadius property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMinRadius(BigDecimal value) {
        this.minRadius = value;
    }

    /**
     * Gets the value of the maxRadius property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaxRadius() {
        return maxRadius;
    }

    /**
     * Sets the value of the maxRadius property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaxRadius(BigDecimal value) {
        this.maxRadius = value;
    }

    /**
     * Gets the value of the block property.
     * 
     * @return
     *     possible object is
     *     {@link BlockType }
     *     
     */
    public BlockType getBlock() {
        return block;
    }

    /**
     * Sets the value of the block property.
     * 
     * @param value
     *     allowed object is
     *     {@link BlockType }
     *     
     */
    public void setBlock(BlockType value) {
        this.block = value;
    }

    /**
     * Gets the value of the placement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlacement() {
        return placement;
    }

    /**
     * Sets the value of the placement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlacement(String value) {
        this.placement = value;
    }

    /**
     * Gets the value of the randomizedRadius property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRandomizedRadius() {
        return randomizedRadius;
    }

    /**
     * Sets the value of the randomizedRadius property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRandomizedRadius(Boolean value) {
        this.randomizedRadius = value;
    }

    /**
     * Gets the value of the minRandomizedRadius property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMinRandomizedRadius() {
        return minRandomizedRadius;
    }

    /**
     * Sets the value of the minRandomizedRadius property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMinRandomizedRadius(BigDecimal value) {
        this.minRandomizedRadius = value;
    }

    /**
     * Gets the value of the maxRandomizedRadius property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaxRandomizedRadius() {
        return maxRandomizedRadius;
    }

    /**
     * Sets the value of the maxRandomizedRadius property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaxRandomizedRadius(BigDecimal value) {
        this.maxRandomizedRadius = value;
    }

}
